//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food_Court_Management_System.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public int WalletID { get; set; }
        public System.DateTime TransactionTime { get; set; }
        public decimal TransactionAmount { get; set; }
        public string Type { get; set; }
        public string Note { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Wallet Wallet { get; set; }
    }
}
